### ISSUE TITLE
Why is this tagged "ubuntu" when it sure looks like it requires OS/X?

### ISSUE THREAD

**Issue by rpresser** [mmpub/StarLanes#1]
How can it be built on Ubuntu?

**Comment by mmpub** [comment]
Star Lanes will run on MacOS or Ubuntu. I just tested with Ubuntu and it still builds and executes with the latest Swift release (5.2.4). The instructions for building Ubuntu are at the bottom of the Readme. I plan to make some mods soon and will make Ubuntu build instructions more conspicuous. Enjoy!

**Comment by rpresser** [comment]
Well, okay. Now that I realize it still requires swift, though, I'm going to pass. I don't know nor do I want to learn swift programming. Thanks for replying.
